### ISSUE TITLE
main截图里的字体和主题

### ISSUE THREAD

**Issue by quarkquartet** [seagle0128/dotfiles#10]
main截图里的字体貌似是powerlevel10k而不是pure？这个在目前的脚本里好像没有，我运行的结果也是main那样的。不知是不是用了什么其他的设置？

另外，能否分享下这张图的terminal主题配色？

**Comment by seagle0128** [comment]
截图中是 powerline-rs （或 powerline-go），配色是molokai。
最新配置直接用的pure，可在.zshrc.local中自行修改配置。
