### ISSUE TITLE
不用cd，去任何路径都报 "zsh permission denied"

### ISSUE THREAD

**Issue by Rongjianying** [seagle0128/dotfiles#12]
❯ ~
zsh: permission denied: /Users/jyrong

❯ ./Downloads
zsh: permission denied: ./Downloads

麻烦大佬帮忙看下，感谢！！
（用cd没有问题）

**Comment by seagle0128** [comment]
建议先学习下Linux/Unix知识。你这是在执行程序。

**Comment by Rongjianying** [comment]
首先感谢您提供的dotfile，用的还是挺舒服的。

但是不要这么轻易地就下结论，上面的问题不是您说的那么low的。查了一下，oh my zsh有个插件叫**zsh-syntax-highlighting**，里边会自动设上 _setopt autocd_ ，而您用的是**fast-syntax-highlighting**，没有这个功能。

手动加上 _setopt autocd_ 就可以了，FYI~

**Comment by seagle0128** [comment]
`setopt autocd` 是插件配置增加的功能，`./Downloads`原本就是执行命令。`fast-syntax-highlighting`性能好很多，所以没有采用`zsh-syntax-highlighting`。个人并不建议输入目录自动跳转，会混淆概念。个人习惯吧！
