### ISSUE TITLE
Screenshots

### ISSUE THREAD

**Issue by seagle0128** [seagle0128/dotfiles#4]
- Main
![image](https://user-images.githubusercontent.com/140797/51855591-9717c880-2368-11e9-9270-bbadc3640982.png)

- Git log
![image](https://user-images.githubusercontent.com/140797/51830877-cf4ce600-232b-11e9-9196-c35a59ebe491.png)

**Comment by JohnWick95** [comment]
Hello, what's the emacs theme in the terminal 'main' screenshot?

**Comment by seagle0128** [comment]
mobokai
