### ISSUE TITLE
ubuntu shortcut key of `ctrl+r` can't act like macos

### ISSUE THREAD

**Issue by nehcuh** [seagle0128/dotfiles#7]
Sorry to disturb. Your dotfiles are really convient configuration. 
When I followed you settings both on MacOS and Ubuntu. Shortcuts of `Ctrl+R` which is to search history commands acts differently.
I've modified you `.zshrc` file, change the default theme `ys` to `powerlevel 10k`. MacOS seems everythings's fine, however, ubuntu seems `Ctrl+R` acts like common `Ctrl+R`, cann't find hisotry commands display.
Do you have any ideas or suggestions?

**Comment by seagle0128** [comment]
I am sure it does work. Please check the configuration of your terminal on Ubuntu.

**Comment by nehcuh** [comment]
Never mind. Even I've reset all configuration, `Ctrl+R` doesn't work! It's quite strange. Seems there's some confict.
