### ISSUE TITLE
error in .zshrc: ".zshrc: no such hash table element: fd"

### ISSUE THREAD

**Issue by fpGHwd** [seagle0128/dotfiles#8]
When run the script in quickstart
`sh -c "$(curl -fsSL https://github.com/seagle0128/dotfiles/raw/master/install.sh)"`

Result: 
`/home/suzumiya/.zshrc:unalias:104: no such hash table element: fd`

Info:
- suzumiya@suzumiya-pc
- OS: Manjaro 19.0.1 Kyria
- Kernel: x86_64 Linux 5.4.22-1-MANJARO
- Uptime: 2h 10m
- Packages: 941
- Shell: zsh 5.8
- Resolution: 1920x1080
- DE: Xfce4
- WM: Xfwm4
- WM Theme: Matcha-sea
- GTK Theme: Matcha-sea [GTK2]
- Icon Theme: Papirus-Maia
- Font: Noto Sans CJK SC 10
- Disk: 6.9G / 52G (14%)
- CPU: Intel Core i5-8250U @ 4x 1.8GHz
- GPU: llvmpipe (LLVM 9.0.1, 256 bits)
- RAM: 1475MiB / 5982MiB

It seems that the script was not executed to the last line.

Moreover I noticed line 39 in the script(.zshrc)
`command -v fdfind >/dev/null 2>&1 && alias fd='fdfind'
`.
But I found no fdfind command in linux and pacman has no such command as well.

Looking forward for any solution and many thanks!

**Comment by seagle0128** [comment]
Wired... `fd` is an alias in `oh-my-zsh`, which conflicts with `fd-find`.

```shell
# in ~/.antigen/bundles/robbyrussell/oh-my-zsh/plugins/common-aliases/common-aliases.plugin.zsh
alias fd='find . -type d -name'
```

I will add a check to address this issue.
